version: "3.8"

services:
  web:
    image: jekyll/jekyll:4
    container_name: jekyll_starter
    command: jekyll serve --watch --force_polling --verbose --incremental --trace
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
